import ladhakImg from "../assets/images/ladhak.jpg";
import shimla from "../assets/images/shimla.jpg";
import rishikesh from "../assets/images/rishikesh.jpg";
import kasol from "../assets/images/kasol.jpg";
import dharmshala from "../assets/images/dharmshala.jpg";
import nanital from "../assets/images/nanital.jpg";

export const indiaDestinations = [
  {
    id: 'manali',
    name: 'Manali',
    slug: 'manali',
    description: 'Snow-capped peaks, pine forests, and cozy eco-cabins in the Kullu Valley.',
    image: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=800&q=85',
    stayCount: 142,
    popular: true,
    region: 'Himachal Pradesh',
  },
  {
    id: 'shimla',
    name: 'Shimla',
    slug: 'shimla',
    description: 'Colonial charm meets Himalayan views — perfect for a sustainable hill retreat.',
    image: shimla,
    stayCount: 98,
    popular: true,
    region: 'Himachal Pradesh',
  },
  {
    id: 'mussoorie',
    name: 'Mussoorie',
    slug: 'mussoorie',
    description: 'The Queen of Hills offers misty mornings and heritage homestays above the Doon Valley.',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=85',
    stayCount: 76,
    popular: true,
    region: 'Uttarakhand',
  },
  {
    id: 'nainital',
    name: 'Nainital',
    slug: 'nainital',
    description: 'Lake-side eco-lodges surrounded by oak forests and tranquil mountain air.',
    image: nanital,
    stayCount: 64,
    popular: true,
    region: 'Uttarakhand',
  },
  {
    id: 'kasol',
    name: 'Kasol',
    slug: 'kasol',
    description: 'Parvati Valley vibes — riverside camps, wooden cottages, and off-grid living.',
    image: kasol,
    stayCount: 53,
    popular: false,
    region: 'Himachal Pradesh',
  },
  {
    id: 'rishikesh',
    name: 'Rishikesh',
    slug: 'rishikesh',
    description: 'Yoga capital on the Ganges — ashram stays, rafting, and riverside eco-resorts.',
    image: rishikesh,
    stayCount: 118,
    popular: false,
    region: 'Uttarakhand',
  },
  {
    id: 'dharamshala',
    name: 'Dharamshala',
    slug: 'dharamshala',
    description: 'Tibetan culture, tea gardens, and mountain homestays below the Dhauladhar range.',
    image: dharmshala,
    stayCount: 87,
    popular: false,
    region: 'Himachal Pradesh',
  },
  {
    id: 'leh-ladakh',
    name: 'Leh Ladakh',
    slug: 'leh-ladakh',
    description: 'High-altitude desert landscapes, monasteries, and solar-powered mountain camps.',
    image: ladhakImg,
    stayCount: 71,
    popular: false,
    region: 'Ladakh',
  },
  {
    id: 'srinagar',
    name: 'Srinagar',
    slug: 'srinagar',
    description: 'Heritage houseboats on Dal Lake and beautiful Mughal gardens.',
    image: 'https://images.unsplash.com/photo-1566224340124-7888b5324c40?w=800&q=85',
    stayCount: 84,
    popular: true,
    region: 'Jammu & Kashmir',
  },
  {
    id: 'gulmarg',
    name: 'Gulmarg',
    slug: 'gulmarg',
    description: 'Meadow of flowers, premium skiing, and snowy mountain pines.',
    image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=85',
    stayCount: 42,
    popular: false,
    region: 'Jammu & Kashmir',
  },
  {
    id: 'auli',
    name: 'Auli',
    slug: 'auli',
    description: 'Alpine ski slopes and majestic views of Nanda Devi mountains.',
    image: 'https://images.unsplash.com/photo-1542718610-a1d656a18855?w=800&q=85',
    stayCount: 36,
    popular: false,
    region: 'Uttarakhand',
  },
  {
    id: 'spiti-valley',
    name: 'Spiti Valley',
    slug: 'spiti-valley',
    description: 'High-altitude desert mountains, suspension bridges, and ancient monasteries.',
    image: 'https://images.unsplash.com/photo-1509316781280-0255d2b4d8a8?w=800&q=85',
    stayCount: 28,
    popular: false,
    region: 'Himachal Pradesh',
  },
  {
    id: 'mcleod-ganj',
    name: 'McLeod Ganj',
    slug: 'mcleod-ganj',
    description: 'Tibetan culture, Buddhist temples, and pine forest hiking trails.',
    image: 'https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=800&q=85',
    stayCount: 65,
    popular: false,
    region: 'Himachal Pradesh',
  },
  {
    id: 'jaipur',
    name: 'Jaipur',
    slug: 'jaipur',
    description: 'Pink city heritage palaces, historic forts, and traditional havelis.',
    image: 'https://images.unsplash.com/photo-1477587458883-47135fbdb57c?w=800&q=85',
    stayCount: 110,
    popular: true,
    region: 'Rajasthan',
  },
  {
    id: 'udaipur',
    name: 'Udaipur',
    slug: 'udaipur',
    description: 'Romantic city of lakes and grand white marble palaces.',
    image: 'https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?w=800&q=85',
    stayCount: 92,
    popular: true,
    region: 'Rajasthan',
  },
  {
    id: 'jaisalmer',
    name: 'Jaisalmer',
    slug: 'jaisalmer',
    description: 'Golden fort, sand dunes, and luxury desert glamping camps.',
    image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=85',
    stayCount: 56,
    popular: false,
    region: 'Rajasthan',
  },
  {
    id: 'mount-abu',
    name: 'Mount Abu',
    slug: 'mount-abu',
    description: 'Cool hill station in the Aravalli range featuring Dilwara temples.',
    image: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=800&q=85',
    stayCount: 31,
    popular: false,
    region: 'Rajasthan',
  },
  {
    id: 'goa',
    name: 'Goa',
    slug: 'goa',
    description: 'Sandy beaches, coastal palms, and Portuguese-style eco villas.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=85',
    stayCount: 165,
    popular: true,
    region: 'Goa',
  },
  {
    id: 'coorg',
    name: 'Coorg',
    slug: 'coorg',
    description: 'Coffee plantations, misty mountains, and spice-garden treehouses.',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=85',
    stayCount: 104,
    popular: true,
    region: 'Karnataka',
  },
  {
    id: 'ooty',
    name: 'Ooty',
    slug: 'ooty',
    description: 'Rolling green tea gardens and heritage stone cottages.',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=85',
    stayCount: 88,
    popular: false,
    region: 'Tamil Nadu',
  },
  {
    id: 'munnar',
    name: 'Munnar',
    slug: 'munnar',
    description: 'Endless tea estates, wildlife sanctuaries, and misty valleys.',
    image: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=800&q=85',
    stayCount: 120,
    popular: true,
    region: 'Kerala',
  },
  {
    id: 'wayanad',
    name: 'Wayanad',
    slug: 'wayanad',
    description: 'Tropical forests, spice gardens, waterfalls, and eco-treehouses.',
    image: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=800&q=85',
    stayCount: 78,
    popular: false,
    region: 'Kerala',
  },
  {
    id: 'alleppey',
    name: 'Alleppey',
    slug: 'alleppey',
    description: 'Traditional backwaters, houseboats, and lakeside cottages.',
    image: 'https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=800&q=85',
    stayCount: 94,
    popular: true,
    region: 'Kerala',
  },
  {
    id: 'hampi',
    name: 'Hampi',
    slug: 'hampi',
    description: 'Boulder-strewn ruins, historical temples, and riverside camps.',
    image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=85',
    stayCount: 47,
    popular: false,
    region: 'Karnataka',
  },
  {
    id: 'mysore',
    name: 'Mysore',
    slug: 'mysore',
    description: 'Grand palaces, heritage markets, and local farm stays.',
    image: 'https://images.unsplash.com/photo-1528183429752-a97d0bf99404?w=800&q=85',
    stayCount: 68,
    popular: false,
    region: 'Karnataka',
  },
  {
    id: 'pondicherry',
    name: 'Pondicherry',
    slug: 'pondicherry',
    description: 'French colonial quarters, golden beaches, and spiritual retreats.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=85',
    stayCount: 82,
    popular: true,
    region: 'Puducherry',
  },
  {
    id: 'andaman-islands',
    name: 'Andaman Islands',
    slug: 'andaman-islands',
    description: 'Pristine white-sand beaches, coral reefs, and eco beach huts.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=85',
    stayCount: 51,
    popular: true,
    region: 'Andaman & Nicobar',
  },
  {
    id: 'darjeeling',
    name: 'Darjeeling',
    slug: 'darjeeling',
    description: 'Misty tea gardens, toy train, and majestic Kanchenjunga mountain views.',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=85',
    stayCount: 79,
    popular: true,
    region: 'West Bengal',
  },
  {
    id: 'gangtok',
    name: 'Gangtok',
    slug: 'gangtok',
    description: 'Buddhist monasteries, mountain passes, and Sikkimese hospitality.',
    image: 'https://images.unsplash.com/photo-1542718610-a1d656a18855?w=800&q=85',
    stayCount: 62,
    popular: false,
    region: 'Sikkim',
  },
  {
    id: 'shillong',
    name: 'Shillong',
    slug: 'shillong',
    description: 'Scotland of the East - pine groves, crystal rivers, and green peaks.',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=85',
    stayCount: 58,
    popular: true,
    region: 'Meghalaya',
  }
];

export const destinationServiceLocal = {
  getAll: () => Promise.resolve(indiaDestinations),
  getPopular: () => Promise.resolve(indiaDestinations.filter((d) => d.popular)),
  search: (query) => {
    const q = query.toLowerCase().trim();
    if (!q) return Promise.resolve(indiaDestinations);
    return Promise.resolve(
      indiaDestinations.filter(
        (d) =>
          d.name.toLowerCase().includes(q) ||
          d.description.toLowerCase().includes(q) ||
          d.region.toLowerCase().includes(q)
      )
    );
  },
};
